# Generated by Django 5.0.1 on 2024-01-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='adam', max_length=15, verbose_name='name')),
                ('body', models.CharField(db_index=True, default='Hi', max_length=20, verbose_name='body')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
